services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - telemetry-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - telemetry-net

  f1-exporter:
    build: .
    ports:
      - "18000:18000"
    env_file:
      - .env
    networks:
      - telemetry-net

networks:
  telemetry-net:
    driver: bridge
